version: '3'

services:
  prod:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: dashboard-prod
    restart: always
    environment:
      NODE_ENV: 'production'
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB_PROD}
      MONGO_DB_USER: ${MONGO_DB_USER_PROD}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD_PROD}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET_PROD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.dashboard-redirect.rule=Host(`dashboard.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-redirect.middlewares=redirect@file"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.tls=true"
    depends_on:
      - mongo
    networks:
      - web

  dev:
    container_name: dev
    build:
      context: .
      args:
        CLIENT_PORT: ${CLIENT_PORT}
        SERVER_PORT: ${SERVER_PORT}
      dockerfile: Dockerfile.dev
    image: dashboard-dev
    restart: always
    volumes:
      - ./server:/home/node/app
      - ./client:/home/node/app/client
    environment:
      NODE_ENV: 'development'
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB_DEV}
      MONGO_DB_USER: ${MONGO_DB_USER_DEV}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD_DEV}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET_DEV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.dashboard-server-dev-redirect.rule=Host(`dev-server.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-server-dev-redirect.middlewares=redirect@file"
      - "traefik.http.routers.dashboard-server-dev.rule=Host(`dev-server.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-server-dev.tls=true"
      - "traefik.http.routers.dashboard-client-dev-redirect.rule=Host(`dev-server.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-client-dev-redirect.middlewares=redirect@file"
      - "traefik.http.routers.dashboard-client-dev.rule=Host(`dev-client.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-client-dev.tls=true"
      - "traefik.http.routers.dashboard-server-dev-redirect.service=dashboard-server-dev"
      - "traefik.http.routers.dashboard-client-dev-redirect.service=dashboard-client-dev"
      - "traefik.http.routers.dashboard-server-dev.service=dashboard-server-dev"
      - "traefik.http.routers.dashboard-client-dev.service=dashboard-client-dev"
      - "traefik.http.services.dashboard-server-dev.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.services.dashboard-client-dev.loadbalancer.server.port=${CLIENT_PORT}"
    networks:
      - web
    depends_on:
      - mongo
    command: /home/node/app/dev-start.sh

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - web
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_PROD: ${MONGO_DB_PROD}
      MONGO_DB_USER_PROD: ${MONGO_DB_USER_PROD}
      MONGO_DB_PASSWORD_PROD: ${MONGO_DB_PASSWORD_PROD}
      MONGO_DB_DEV: ${MONGO_DB_DEV}
      MONGO_DB_USER_DEV: ${MONGO_DB_USER_DEV}
      MONGO_DB_PASSWORD_DEV: ${MONGO_DB_PASSWORD_DEV}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    command: --smallfiles

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.mongo-redirect.rule=Host(`mongo.${DOMAIN}`)"
      - "traefik.http.routers.mongo-redirect.middlewares=redirect@file"
      - "traefik.http.routers.mongo.rule=Host(`mongo.${DOMAIN}`)"
      - "traefik.http.routers.mongo.tls=true"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on: 
      - mongo

networks:
  web:
    external: true
